### PR TITLE
Call procs when you try to get plain hash config

### PR DESCRIPTION
**Pull request by nodecarter**

### CODE REVIEW

**Comment by inem** [comment]
@nodecarter can you explain what problem it fixes?

**Comment by nodecarter** [comment]
I had some config block which should read from ENV.
```ruby
  google_cloud do
      ocr_credentials do
        type 'service_account'
        project_id 'optical-character-recognition'
        private_key_id -> { ENV.fetch('GOOGLE_OCR_PRIVATE_KEY_ID') }
        private_key -> { ENV.fetch('GOOGLE_OCR_PRIVATE_KEY') }
        ...
    end
  end
```

And then I want to use `ocr_credentials` as a simple hash.

```ruby
Google::Cloud::Vision.new(project: project_id, keyfile: configus.google_cloud.ocr_credentials.to_hash)
```

**Comment by zzet** [comment]
@nodecarter I'd like to suggest you to check the gem https://github.com/zzet/persey

**Comment by nodecarter** [comment]
@zzet thank you! 👍

**Pull request closed without merging**
